version: 2
updates:
  # Monitora as dependências do ecossistema Docker (Dockerfiles)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"

  # Monitora as dependências do Front-end (Node/npm)
  - package-ecosystem: "npm"
    directory: "/modules/front-end"
    schedule:
      interval: "weekly"
